## Acordeon actividad 2

In [1]:
import pandas as pd

In [2]:
#Despues de importar pandas lo siguiente es cargar el archivo tipo csv en la misma carpeta *ASEGURATE DE GUARDAR ESTA NOTA TMB*
df = pd.read_csv("base_generica_pandas.csv")

In [3]:
#el .head() sirve para ver los primeros 5 datos de el encabezado, pero si dentro de el parentesis agregas un numero, te despliega los primeros datos en proporcion al numero solicitado 
df.head(13)

      col1  col2  col3  col4 col5   col6   col7  col8 col9  col10
0   380.79    49  56.4     1    B    Sur  0.294     5   No   Alto
1   951.21    56  13.0     9    A  Oeste  0.996     2   Sí  Medio
2   734.67    49  57.2     2    C  Norte  0.697     5   Sí   Alto
3   602.67    21  63.9     0    A  Norte  0.384     3   Sí   Alto
4   164.46    47  37.4     7    D    Sur  0.737     3   Sí  Medio
5   164.43    54  60.2     2    D   Este  0.915     3   No   Alto
6    67.50    40  78.1     9    A    Sur  0.959     3   Sí   Bajo
7   867.51    56  55.9     6    A  Norte  0.058     1   No   Bajo
8   605.10    62  40.6     9    A  Oeste  0.395     3   No  Medio
9   710.99    32  42.2     4    A    Sur  0.107     4   Sí  Medio
10   30.38    60  50.2     9    D  Norte  0.336     4   No  Medio
11  970.21    46  55.7     4    B    Sur  0.170     1   No   Bajo
12  834.12    53  50.9     6    A   Este  0.647     3   No   Alto

In [4]:
#Por el contrario el .tail() despliega los ultimos 5 datos de la tabla, sucede lo mismo con los parentesis, llenalo de el numero que necesites 
df.tail(13)

      col1  col2  col3  col4 col5   col6   col7  col8 col9  col10
87  641.18    26  68.0     0    C   Este  0.726     2   No   Alto
88  888.34    23  52.2     9    B  Oeste  0.547     1   No  Medio
89  477.49    33  52.1     7    A  Norte  0.451     4   Sí   Bajo
90  128.40    46  55.3     9    C  Oeste  0.910     3   No  Medio
91  716.11    20  21.8     9    C   Este  0.298     2   No  Medio
92  763.18    37  64.5     9    A   Este  0.524     1   No   Bajo
93  565.66    53  42.3     1    C  Oeste  0.698     5   Sí   Alto
94  773.26    36  68.2     2    C  Norte  0.796     4   Sí   Alto
95  498.86    43  47.7     8    B    Sur  0.459     2   Sí   Bajo
96  527.51    20  44.4     6    C   Este  0.842     2   Sí   Alto
97  433.27    36  30.6     3    D  Norte  0.769     3   Sí   Bajo
98   35.16    37  38.5     9    A  Norte  0.066     3   Sí   Bajo
99  116.81    49  56.3     4    B    Sur  0.046     5   Sí   Bajo

In [ ]:
#Para saber el tamaño de la tabla existe el .shape el cual te dice de cuanto x cuanto es la tabla (sin parentesis, no es accion)
df.shape

(100, 10)

In [6]:
#No sabes el nombre de los encabezados de las columnas? no te preocupes brodi ya que con .columns puedes descubrirlo
df.columns

Index(['col1', 'col2', 'col3', 'col4', 'col5', 'col6', 'col7', 'col8', 'col9',
       'col10'],
      dtype='str')

In [7]:
#Para saber mas que solo los nombres de el encabezado usa .info() el cual te dara datos como cuanto pesa la tabla, nombres de columnas, espacios nulos y el tipo de datos
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 100 entries, 0 to 99
Data columns (total 10 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   col1    100 non-null    float64
 1   col2    100 non-null    int64
 2   col3    100 non-null    float64
 3   col4    100 non-null    int64
 4   col5    100 non-null    str
 5   col6    100 non-null    str
 6   col7    100 non-null    float64
 7   col8    100 non-null    int64
 8   col9    100 non-null    str
 9   col10   100 non-null    str
dtypes: float64(3), int64(3), str(4)
memory usage: 7.9 KB

In [8]:
#Ahora seleccionaremos la columna que quieras de la tabla, para eso usaremos corchetes, usaremos de ejemplo la columna col1
df["col1"]

0     380.79
1     951.21
2     734.67
3     602.67
4     164.46
       ...
95    498.86
96    527.51
97    433.27
98     35.16
99    116.81
Name: col1, Length: 100, dtype: float64

In [10]:
#Si quieres seleccionar 2 columnas puedes hacerlo separandolas con un simple coma, no olvides los [""] extra 
df[["col1","col3"]]

      col1  col3
0   380.79  56.4
1   951.21  13.0
2   734.67  57.2
3   602.67  63.9
4   164.46  37.4
..     ...   ...
95  498.86  47.7
96  527.51  44.4
97  433.27  30.6
98   35.16  38.5
99  116.81  56.3

[100 rows x 2 columns]

In [11]:
#En caso que requieras varias columnas, dales un nombre
Grupo_Columnas = ["col1","col2","col3","col5"]
df[Grupo_Columnas]

      col1  col2  col3 col5
0   380.79    49  56.4    B
1   951.21    56  13.0    A
2   734.67    49  57.2    C
3   602.67    21  63.9    A
4   164.46    47  37.4    D
..     ...   ...   ...  ...
95  498.86    43  47.7    B
96  527.51    20  44.4    C
97  433.27    36  30.6    D
98   35.16    37  38.5    A
99  116.81    49  56.3    B

[100 rows x 4 columns]

In [13]:
#A continuación filtraremos datos de una columna con una condicion donde nos aviente True o False, si la columna tiene "Sur" la marcara como True, de lo contrario False
df["col6"] == "Sur"

0      True
1     False
2     False
3     False
4      True
      ...
95     True
96    False
97    False
98    False
99     True
Name: col6, Length: 100, dtype: bool

In [14]:
#Para acceder a la tabla de la columna condicionada solo se necesita:
df[df["col6"] == "Sur"]

      col1  col2  col3  col4 col5 col6   col7  col8 col9  col10
0   380.79    49  56.4     1    B  Sur  0.294     5   No   Alto
4   164.46    47  37.4     7    D  Sur  0.737     3   Sí  Medio
6    67.50    40  78.1     9    A  Sur  0.959     3   Sí   Bajo
9   710.99    32  42.2     4    A  Sur  0.107     4   Sí  Medio
11  970.21    46  55.7     4    B  Sur  0.170     1   No   Bajo
13  220.22    30  57.5     8    A  Sur  0.388     3   Sí   Bajo
14  190.01    49  47.8     4    D  Sur  0.229     3   No  Medio
18  437.63    19  51.6     0    C  Sur  0.453     2   No  Medio
24  461.51    61  22.3     0    D  Sur  0.133     4   Sí  Medio
33  949.40    18  33.3     5    A  Sur  0.165     2   No  Medio
39  445.75    23  52.2     9    A  Sur  0.750     2   Sí   Alto
42   44.04    26  49.8     6    D  Sur  0.569     3   No   Bajo
43  910.23    54  56.2     3    D  Sur  0.064     5   Sí  Medio
46  318.59    61  69.5     6    A  Sur  0.014     4   No   Alto
50  969.89    49  49.9     4    D  Sur  0.750     5   No   Bajo
52  940.10    58  72.2     1    A  Sur  0.585     2   Sí   Alto
53  895.88    29  56.0     3    A  Sur  0.726     4   No   Alto
65  547.27    50  23.8     0    C  Sur  0.022     3   Sí  Medio
73  817.31    49  43.3     2    C  Sur  0.792     2   Sí   Bajo
75  731.72    28  39.1     4    D  Sur  0.480     1   No   Bajo
76  773.56    34  23.0     2    A  Sur  0.421     1   Sí   Bajo
85  331.93    33  80.0     2    C  Sur  0.555     2   Sí  Medio
95  498.86    43  47.7     8    B  Sur  0.459     2   Sí   Bajo
99  116.81    49  56.3     4    B  Sur  0.046     5   Sí   Bajo

In [16]:
#Si ocupas mas de una condicion tu tranqui, solo separalas con parentesis y conectalos con operadores 
df[(df["col10"]=="Alto") & (df["col9"]!="No")]

      col1  col2  col3  col4 col5   col6   col7  col8 col9 col10
2   734.67    49  57.2     2    C  Norte  0.697     5   Sí  Alto
3   602.67    21  63.9     0    A  Norte  0.384     3   Sí  Alto
20  615.73    62  63.8     5    D  Oeste  0.280     3   Sí  Alto
29   55.99    45  38.0     2    A  Norte  0.919     5   Sí  Alto
39  445.75    23  52.2     9    A    Sur  0.750     2   Sí  Alto
45  665.90    59  63.1     4    B   Este  0.134     2   Sí  Alto
47  524.87    41  29.8     9    C   Este  0.075     1   Sí  Alto
52  940.10    58  72.2     1    A    Sur  0.585     2   Sí  Alto
59  332.08    19  55.1     7    B  Norte  0.275     3   Sí  Alto
63  363.19    54  41.0     6    C  Norte  0.047     2   Sí  Alto
66  149.51    18  29.9    10    D  Norte  0.498     3   Sí  Alto
71  206.73    49  34.6     0    A  Oeste  0.968     1   Sí  Alto
79  124.71    22  42.3     7    A  Oeste  0.805     1   Sí  Alto
93  565.66    53  42.3     1    C  Oeste  0.698     5   Sí  Alto
94  773.26    36  68.2     2    C  Norte  0.796     4   Sí  Alto
96  527.51    20  44.4     6    C   Este  0.842     2   Sí  Alto

In [17]:
#Ahora ordenaremos las columnas del dataframe como queramos, de menos a mayor o viceversa 
#En este caso la ordenara de menor a mayor por default, en caso de querer lo contrario especificar 
df.sort_values("col1")

      col1  col2  col3  col4 col5   col6   col7  col8 col9  col10
72   15.47    23  63.2     0    D  Norte  0.088     1   No   Alto
10   30.38    60  50.2     9    D  Norte  0.336     4   No  Medio
98   35.16    37  38.5     9    A  Norte  0.066     3   Sí   Bajo
42   44.04    26  49.8     6    D    Sur  0.569     3   No   Bajo
58   54.78    34  48.1     0    D   Este  0.251     3   No   Alto
..     ...   ...   ...   ...  ...    ...    ...   ...  ...    ...
1   951.21    56  13.0     9    A  Oeste  0.996     2   Sí  Medio
34  965.98    44  63.0     8    C  Oeste  0.411     1   Sí   Bajo
50  969.89    49  49.9     4    D    Sur  0.750     5   No   Bajo
11  970.21    46  55.7     4    B    Sur  0.170     1   No   Bajo
69  987.02    61  70.8     1    C  Norte  0.308     4   No   Bajo

[100 rows x 10 columns]

In [18]:
#En caso de solicitarlo de mayor a menor
df.sort_values("col1", ascending = False)

      col1  col2  col3  col4 col5   col6   col7  col8 col9  col10
69  987.02    61  70.8     1    C  Norte  0.308     4   No   Bajo
11  970.21    46  55.7     4    B    Sur  0.170     1   No   Bajo
50  969.89    49  49.9     4    D    Sur  0.750     5   No   Bajo
34  965.98    44  63.0     8    C  Oeste  0.411     1   Sí   Bajo
1   951.21    56  13.0     9    A  Oeste  0.996     2   Sí  Medio
..     ...   ...   ...   ...  ...    ...    ...   ...  ...    ...
58   54.78    34  48.1     0    D   Este  0.251     3   No   Alto
42   44.04    26  49.8     6    D    Sur  0.569     3   No   Bajo
98   35.16    37  38.5     9    A  Norte  0.066     3   Sí   Bajo
10   30.38    60  50.2     9    D  Norte  0.336     4   No  Medio
72   15.47    23  63.2     0    D  Norte  0.088     1   No   Alto

[100 rows x 10 columns]

In [ ]:
#Para calcular la media se usa .mean()
df["col1"].mean()

np.float64(475.4793000000001)

In [20]:
#maximo o minimo max o min
df["col1"].max()

np.float64(987.02)

In [21]:
df["col1"].min()

np.float64(15.47)

In [22]:
#Para el analizar variables de texto utilizamos value_counts() para contar cuántas veces aparece cada valor, unique() para obtener una lista de los valores distintos (osea que variables hay) o nunique() para saber la cantidad exacta de valores diferentes (cuantas variables hay).
ContarSubCategorias = df["col10"].value_counts()
display(ContarSubCategorias)

col10
Bajo     36
Alto     34
Medio    30
Name: count, dtype: int64

In [23]:
ValorUnico = df["col9"].unique()
ValorUnico

<StringArray>
['No', 'Sí']
Length: 2, dtype: str

In [24]:
ValorNoUnico= df["col9"].nunique()
ValorNoUnico

2

In [27]:
#EjEMPLOS DE USOS DE EL .GROUPBY
df.groupby("col5")[["col1","col2"]].mean()

            col1       col2
col5
A     471.190882  37.470588
B     474.602000  43.333333
C     501.510769  42.192308
D     454.765200  41.760000

In [29]:
df.groupby(["col10","col5","col9"])[["col1","col3"]].mean()

                       col1       col3
col10 col5 col9
Alto  A    No    713.192500  50.525000
           Sí    395.991667  50.533333
      B    No    389.716667  44.066667
           Sí    498.990000  59.100000
      C    No    505.217500  57.275000
           Sí    581.526667  47.150000
      D    No    379.355714  53.914286
           Sí    382.620000  46.850000
Bajo  A    No    423.932222  50.100000
           Sí    343.237143  49.000000
      B    No    740.536667  40.433333
           Sí    254.590000  50.200000
      C    No    987.020000  70.800000
           Sí    525.102000  52.260000
      D    No    585.535000  36.400000
           Sí    468.462500  33.825000
Medio A    No    440.346000  43.600000
           Sí    790.663333  37.166667
      B    No    549.550000  61.466667
           Sí    317.870000  26.600000
      C    No    350.266000  50.720000
           Sí    433.078000  49.980000
      D    No    479.392500  45.400000
           Sí    453.710000  47.275000

In [30]:
#Para crear o modificar columnas nuevas
df["suma_col1_col3"] = df["col1"] + df["col3"]
df[["col1", "col3", "suma_col1_col3"]].head()

     col1  col3  suma_col1_col3
0  380.79  56.4          437.19
1  951.21  13.0          964.21
2  734.67  57.2          791.87
3  602.67  63.9          666.57
4  164.46  37.4          201.86

In [31]:
#Combinar operaciones
Final = df[df["col6"] == "Sur"].groupby("col10")[["col1"]].mean().sort_values("col1",ascending=False)
Final

             col1
col10
Alto   596.222000
Medio  522.603333
Bajo   521.012000